# Generated by Django 3.2.13 on 2022-07-01 12:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_land_price_alter_laundry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='leaders/thumbnails/'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='leaders/thumbnails/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='leaders/thumbnails/'),
        ),
    ]
